# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Checks

on:
  push:
    branches: [ master, beta ]
  pull_request:
    branches: [ master, beta ]

jobs:
  unit_tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16, 18 ]
        # TODO: Find a better action, this one is limited to v1.33.1
        # See https://github.com/maximousblk/setup-deno/issues
        deno-version: [ 'v1.33.1' ]

    steps:
    - uses: actions/checkout@v3

    # Install Node
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: node -v

    # Install Deno
    - name: Setup Deno ${{ matrix.deno-version }}
      uses: maximousblk/setup-deno@v2
      with:
        deno-version: ${{ matrix.deno-version }}
    - run: deno -V

    # Install deps
    - run: npm ci

    # Build and test dnt packages
    - run: npm run build:types   # browser tests will need this to be built
    - run: npm run build:server  # dnt will test everything in Node too

    # Test packages
    - run: npm run test:browser
