# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, beta ]
  pull_request:
    branches: [ master, beta ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16, 18 ]
        deno-version: [ 'v1.36.x' ]

    steps:
    - uses: actions/checkout@v3

    # Node
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run bootstrap:ci
    - run: npm run test:browser

    # Deno
    - name: Setup Deno (${{ matrix.deno-version }})
      uses: maximousblk/setup-deno@v2
      with:
        deno-version: ${{ matrix.deno-version }}
    - run: deno -V
    - run: npm run test:server
    - run: npm run test:types
    - run: npm run build:server
    - run: npm run build:types
